"""empty message

Revision ID: 741459e49b3b
Revises: 6ef1c49c7ba5
Create Date: 2023-04-12 16:00:47.298743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741459e49b3b'
down_revision = '6ef1c49c7ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
